import { Clasificacion } from "./clasificacion";

export const CLASIFICACION: Clasificacion[] = [
    {
        equipo: "real madrid",
        pj: 10,
        g: 8,
        e: 1,
        p: 1,
        gf: 21,
        gc: 7,
    },
    {
        equipo: "girona",
        pj: 10,
        g: 8,
        e: 1,
        p: 1,
        gf: 24,
        gc: 13, 
    },
    {
        equipo: "barcelona",
        pj: 10,
        g: 7,
        e: 3,
        p: 0,
        gf: 22,
        gc: 10,
    },
    {
        equipo: "atlético madrid",
        pj: 9,
        g: 7,
        e: 1,
        p: 1,
        gf: 23,
        gc: 8,
    },
    {
        equipo: "real sociedad",
        pj: 10,
        g: 5,
        e: 3,
        p: 2,
        gf: 18,
        gc: 12,
    },
    {
        equipo: "athletic",
        pj: 10,
        g: 5,
        e: 2,
        p: 3,
        gf: 16,
        gc: 10,
    },
    {
        equipo: "rayo vallecano",
        pj: 10,
        g: 4,
        e: 4,
        p: 2,
        gf: 12,
        gc: 13,
    },
    {
        equipo: "valencia C.F.",
        pj: 10,
        g: 4,
        e: 2,
        p: 4,
        gf: 12,
        gc: 11,
    },
    {
        equipo: "betis",
        pj: 10,
        g: 3,
        e: 5,
        p: 2,
        gf: 12,
        gc: 14,
    },
    {
        equipo: "osasuna",
        pj: 10,
        g: 4,
        e: 1,
        p: 5,
        gf: 11,
        gc: 14,
    },
    {
        equipo: "getafe",
        pj: 10,
        g: 2,
        e: 5,
        p: 3,
        gf: 13,
        gc: 16,
    },
    {
        equipo: "U.D. Las Palmas",
        pj: 10,
        g: 3,
        e: 2,
        p: 5,
        gf: 6,
        gc: 9,
    },
    {
        equipo: "sevilla",
        pj: 9,
        g: 2,
        e: 3,
        p: 4,
        gf: 14,
        gc: 13,
    },
    {
        equipo: "villareal",
        pj: 10,
        g: 2,
        e: 3,
        p: 5,
        gf: 12,
        gc: 16,
    }
]